[package]
name = "nacos_rust"
version = "0.1.0"
authors = ["heqingpan <heqingpan@126.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = {version = "1", features = ["derive"]}
serde_json = "1"
serde_urlencoded = "0.6"
actix-web="3"
actix-http="2"
actix = "0.10"
actix-rt = "1"
env_logger = "0.7"
rust-crypto="0.2"
tokio = {version="0.2", features=["full"]}
chrono = {version = "0.4", features =["serde"] }
