name: Docker Publish

on:
  push:
    branches:
      - master 
    tags: [ 'v*' ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            changed:
              - 'Cargo.toml'
              - 'src/**'
              - 'build.rs'
              - 'Dockerfile'
              - '.github/workflows/docker.yml'
      -
        name: Set up QEMU
        if: ${{ steps.changes.outputs.changed == 'true' || startsWith(github.ref, 'refs/tags/') }}
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        if: ${{ steps.changes.outputs.changed == 'true' || startsWith(github.ref, 'refs/tags/') }}
        uses: docker/setup-buildx-action@v2
      - uses: docker/metadata-action@v4
        if: ${{ steps.changes.outputs.changed == 'true' || startsWith(github.ref, 'refs/tags/') }}
        id: meta
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/rnacos
      -
        name: Login to Docker Hub
        if: ${{ steps.changes.outputs.changed == 'true' || startsWith(github.ref, 'refs/tags/') }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        if: ${{ steps.changes.outputs.changed == 'true' || startsWith(github.ref, 'refs/tags/') }}
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
